name: ML Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas scikit-learn flake8 black mypy

    - name: Lint with flake8
      run: |
        flake8 tests --count --exit-zero

    - name: Format check with black
      run: |
        black --check .

    - name: Run data tests
      run: |
        pytest tests/test_data.py -v

    - name: Run model tests
      run: |
        pytest tests/test_model.py -v
